name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG=$(git rev-parse --short HEAD)
        docker build . --file Dockerfile --tag python-flask:$TAG 
        docker run -d -p 5000:50000 python-flask:$TAG
        curl -k --fail 127.0.0.1:5000
